# Generated by Django 3.1.3 on 2020-11-24 07:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together={('order', 'user')},
        ),
    ]
