# Generated by Django 3.1.3 on 2020-11-24 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20201124_0745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='type',
            new_name='name',
        ),
    ]
