# Generated by Django 3.1.3 on 2020-11-28 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20201124_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_order', to='webapp.order'),
        ),
    ]
