# Generated by Django 3.1.3 on 2020-11-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20201128_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('enabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['-price']},
        ),
    ]
