# Generated by Django 3.1.3 on 2020-12-05 15:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0008_auto_20201201_1442'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('type', 'user')},
        ),
    ]
